language: 
  - node_js

node_js:  
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/numbers

before_script:
 - psql -c 'create database numbers;' -U postgres
 - psql -U postgres -d numbers -a -f table.sql

services:
  - postgresql